# Generated by Django 2.1.7 on 2019-03-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='club_id',
        ),
        migrations.AlterField(
            model_name='clubs',
            name='club_name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
