# Generated by Django 2.1.7 on 2019-04-29 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubs',
            old_name='favorite_user',
            new_name='user_favorite',
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_day',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
