# Generated by Django 2.1.3 on 2018-12-26 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2500)),
                ('event_nm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainProject.Events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainProject.Users')),
            ],
        ),
    ]
