# Generated by Django 2.1.7 on 2019-04-25 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
