# Generated by Django 2.1.7 on 2019-03-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0002_auto_20190307_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteclubs',
            name='club',
        ),
        migrations.RemoveField(
            model_name='favoriteclubs',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavoriteClubs',
        ),
    ]
