# Generated by Django 2.1.7 on 2019-04-25 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0002_auto_20190425_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_day',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
