# Generated by Django 2.2 on 2019-04-10 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainProject', '0003_auto_20190311_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='fav',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
