# Generated by Django 2.2 on 2019-04-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0004_clubs_fav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubs',
            old_name='fav',
            new_name='favori',
        ),
    ]
