# Generated by Django 2.1.3 on 2018-12-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0005_auto_20181231_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='event_nm',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(),
        ),
    ]
