# Generated by Django 2.2 on 2019-04-24 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainProject', '0005_auto_20190416_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='favori',
        ),
        migrations.AddField(
            model_name='clubs',
            name='favorite_user',
            field=models.ManyToManyField(related_name='favorite_clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
