# Generated by Django 2.1.3 on 2019-01-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0006_auto_20181231_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='club_emblem',
            field=models.ImageField(upload_to='uniqueEmblem'),
        ),
    ]
